services:
  - type: web
    name: telegram-bot
    runtime: python
    pythonVersion: 3.12.3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
